# Generated by Django 5.1.1 on 2024-10-18 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="record",
            name="comment",
            field=models.TextField(blank=True, null=True),
        ),
    ]
